name: Stale monitor

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  stale:
    name: Stale
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: Automattic/vip-actions/stale@add/stale-action
        with:
          days-before-stale: "30"
